In [15]:
import numpy as np

evals = np.load('logs/exp_1/eval_logs/evaluations.npz')

In [16]:
print(evals.files)
print(evals['timesteps'])
print(evals['results'].astype(np.int32))
print(evals['ep_lengths'])

['timesteps', 'results', 'ep_lengths']
[  96000  192000  288000  384000  480000  576000  672000  768000  864000
  960000 1056000 1152000 1248000 1344000 1440000 1536000 1632000 1728000
 1824000 1920000 2016000 2112000 2208000 2304000 2400000 2496000 2592000
 2688000 2784000 2880000 2976000 3072000 3168000 3264000 3360000 3456000
 3552000 3648000 3744000 3840000 3936000 4032000 4128000 4224000 4320000
 4416000 4512000 4608000 4704000 4800000 4896000 4992000 5088000 5184000
 5280000 5376000 5472000 5568000 5664000 5760000 5856000 5952000 6048000
 6144000]
[[   0    0    0    0    0]
 [   0    0    0    0    0]
 [   0    0    0    0    0]
 [   0    0    0    0    0]
 [   0    0    0   10    0]
 [   0    0    0    0    0]
 [   0    1    0   40   50]
 [   0  146  203    0  637]
 [   0    0    1    0    0]
 [   0    0    0   15    0]
 [   0    0    0  441    0]
 [   0    2   15   94    0]
 [   0    0  119  194  921]
 [   0    0    0  322   57]
 [   0  151  223  313  271]
 [   0    0   26  31